// Command logogen converts an ANSI-colored xterm-256 text banner into a
// generated Go source file exposing a structured cell grid (rune + palette
// index) instead of raw escape sequences.
//
// GIVEN a source file using only the "ESC[38;5;Nm" (256-color foreground) and
// "ESC[0m" (reset) SGR sequences,
// WHEN logogen parses it,
// THEN it writes a gofmt'd Go source file defining
// "var <name> = [][]Cell{...}" (name from -var, default LogoGrid) — one row
// per input line, one Cell per visible rune, carrying that rune and the
// xterm-256 palette index it was colored with (Color: -1 when no color is
// set). The Cell type itself is hand-written where the grid is consumed
// (internal/surfaces/banner), not generated — logogen only emits data, so two
// grids (the full logo and the collapsed wordmark) can share one type via
// two invocations with different -var/-out. Anything that wants to recolor
// the banner (e.g. a color-cycle animation) can walk the grid directly and
// never has to parse ANSI escapes. See logo/README.md for the full
// authoring pipeline.
//
// Any other SGR sequence is left in place (the current color carries over
// unchanged) rather than rejected, so a stray style code doesn't break the
// build — logogen only needs to understand the grammar this repo's banners
// actually use.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
	"text/template"
	"unicode/utf8"
)

const esc = '\x1b'

// cell mirrors the generated Cell type: a rune plus the xterm-256 palette
// index it was colored with, or -1 if no color was set.
type cell struct {
	Rune  rune
	Color int16
}

func main() {
	in := flag.String("in", "logo/agentx.logo", "path to the ANSI-colored source banner")
	out := flag.String("out", "internal/surfaces/banner/logo_generated.go", "path to write the generated Go source")
	pkg := flag.String("pkg", "main", "package name for the generated file")
	varName := flag.String("var", "LogoGrid", "exported variable name for the generated grid")
	flag.Parse()

	src, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintf(os.Stderr, "logogen: %v\n", err)
		os.Exit(1)
	}

	rows := parse(string(src))

	generated, err := render(*pkg, *varName, *in, rows)
	if err != nil {
		fmt.Fprintf(os.Stderr, "logogen: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(*out, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "logogen: %v\n", err)
		os.Exit(1)
	}
}

// parse splits src into lines and each line into cells, tracking the
// currently active xterm-256 foreground color as SGR sequences are consumed.
func parse(src string) [][]cell {
	lines := strings.Split(src, "\n")
	rows := make([][]cell, len(lines))
	for i, line := range lines {
		rows[i] = parseLine(line)
	}
	return rows
}

func parseLine(line string) []cell {
	var row []cell
	color := int16(-1)
	b := []byte(line)
	for i := 0; i < len(b); {
		if b[i] == esc && i+1 < len(b) && b[i+1] == '[' {
			j := i + 2
			for j < len(b) && b[j] != 'm' {
				j++
			}
			if j < len(b) {
				color = applySGR(string(b[i+2:j]), color)
				i = j + 1
				continue
			}
		}
		r, size := utf8.DecodeRune(b[i:])
		row = append(row, cell{Rune: r, Color: color})
		i += size
	}
	return row
}

// applySGR interprets one SGR parameter list ("0", or "38;5;N") and returns
// the resulting current color. Anything else is left unchanged.
func applySGR(params string, color int16) int16 {
	parts := strings.Split(params, ";")
	switch {
	case len(parts) == 1 && parts[0] == "0":
		return -1
	case len(parts) == 3 && parts[0] == "38" && parts[1] == "5":
		if n, err := strconv.Atoi(parts[2]); err == nil && n >= 0 && n <= 255 {
			return int16(n)
		}
	}
	return color
}

var tmpl = template.Must(template.New("logo").Parse(`// Code generated by cmd/logogen from {{.Source}}. DO NOT EDIT.

package {{.Package}}

var {{.Var}} = [][]Cell{
{{- range .Rows}}
	{ {{- range .}}{Rune: {{printf "%q" .Rune}}, Color: {{.Color}}}, {{end}}},
{{- end}}
}
`))

func render(pkg, varName, source string, rows [][]cell) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Package string
		Var     string
		Source  string
		Rows    [][]cell
	}{Package: pkg, Var: varName, Source: source, Rows: rows}); err != nil {
		return nil, err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}
	return formatted, nil
}
