[agentx]
ollama_host = "localhost:11434"
ollama_model = "phi4-mini:3.8b"
ollama_initial_load_timeout_seconds = 120
screen_side = "left"
theme_mode = "Dark Mode"
show_log_locations_on_startup = true
enable_gui_chat = true
auto_stop_tmux_on_gui_exit = true

[agentix]
system_prompts_dir = "system_prompts"
agentix_bench_classification_model = "phi4-mini:3.8b"

[tui]
enable = true
socket = "/tmp/agentx_agentx.tui.nvim.sock"
output_fifo = "/tmp/agentx_agentx.tui_output.fifo"
input_fifo = "/tmp/agentx_agentx.tui_input.fifo"
output_split_ratio = 0.7
write_timeout_sec = 1.0
show_thinking = true
lua = [ "output_win", "input_win",]

[terminal]
exec_mode = "autonomous"

[tool_registry]
search_paths = [ "./agentx_tools.toml", "~/.agentx/agentx_tools.toml",]
